### ISSUE TITLE
[QUESTION] What about basic block with n_instructions < 5?

### ISSUE THREAD

**Issue by bobbyhaliwela** [palmtreemodel/PalmTree#2]
Hi,

I'm asking for a clarity here. The paper described that for CWP, you used w=2 as the value for context window size, w=2 steps before, and w=2 steps after. Does this mean you only sample instruction pairs from basic block with n_instructions >= 5? If i want to prepare my own dataset, does this mean i have to ommit all basic blocks that have n_instructions < 5?

Regards,

**Comment by SidekickLx** [comment]
If the bb has less than 5 instructions. It still can be considered as a "window" In this case, we only sample instruction pairs that within this "incomplete window", the rule is still the same. For instance, if the bb has instructions i1, i2, i3, then we will sample pairs like i1i2, i1i3, and i2i3

**Comment by bobbyhaliwela** [comment]
Thank you for your explanation. Cheers.
