### ISSUE TITLE
Question about experiment reproduction

### ISSUE THREAD

**Issue by ZhangZhuoSJTU** [palmtreemodel/PalmTree#3]
Hi,

Thanks for your excellent work. It is quite interesting and I cannot wait to play with it.

I just notice that you have spent great efforts on developing downstream tasks and I am wondering whether you will release the code of those downstream tasks if possible? 

Best

**Comment by SidekickLx** [comment]
Thanks for the issue. I am not the owner of the downstream tasks and I believe that EKLAVYA and deepVSA have open-sourced their code and dataset. So actually it is not hard for you to feed palmtree and other embeddings into their model. 
Btw, we mentioned that we use an "embedding" layer to further adjust the embedding for the specific downstream models. Actually, it means that we add a full-connect layer between our embedding and their models. And it will help improve the final result a little bit.

**Comment by ZhangZhuoSJTU** [comment]
Thanks for your reply! 

I additionally encounter a pickle unpacking error as follows

```bash
$ CUDA_VISIBLE_DEVICES="1" python how2use.py

Loading Vocab ./palmtree/vocab
Traceback (most recent call last):
  File "how2use.py", line 11, in <module>
    palmtree = utils.UsableTransformer(model_path="./palmtree/transformer.ep19", vocab_path="./palmtree/vocab")
  File "/PalmTree/PalmTree/eval_utils.py", line 59, in __init__
    self.vocab = vocab.WordVocab.load_vocab(vocab_path)
  File "/PalmTree/PalmTree/vocab.py", line 167, in load_vocab
    return pickle.load(f)
ModuleNotFoundError: No module named 'bert_pytorch'
```

I am using the pretrained model there. I search the codebase and cannot find the declaration of `bert_pytorch`. Would you mind helping me check what happened? Thanks for your time in advance.

https://github.com/palmtreemodel/PalmTree/blob/895828099a502195255e71a91f753f8cefe58349/src/train_palmtree.py#L40

https://github.com/palmtreemodel/PalmTree/blob/895828099a502195255e71a91f753f8cefe58349/src/train_palmtree.py#L52

**Comment by ZhangZhuoSJTU** [comment]
Oh, I figured it out. `bert_pytorch` is the obsolete name of 'PalmTree'. 

Hence, how to fix this issue is by:

```bash
$ git clone git@github.com:palmtreemodel/PalmTree.git
$ cd PalmTree
$ ls
LICENSE  README.md  src
$ mv PalmTree.zip . # PalmTree.zip is the pretrained model provided in README
$ unzip PalmTree.zip
$ ls 
LICENSE  PalmTree PalmTree.zip README.md  src
$ cd PalmTree
$ cp -r ../src/palmtree bert_pytorch
$ ls
bert_pytorch  config.py  eval_utils.py  how2use.py  palmtree  __pycache__  vocab.py
$ vim -O vocab.py eval_utils.py  # add "import bert_pytorch" into these two files
$ python how2use.py
```

So far, I can run the example code `how2use.py`. 

Although I believe it is just a temporary fix, anyone encounters the same issue may follow. I hope this also helps the author fix the issue.

**Comment by SidekickLx** [comment]
#1

**Comment by SidekickLx** [comment]
This was mentioned in issue #1  
Because the palmtree is build on the top of the bert-pytorch library. When I trained and saved the model, I haven't changed the module name yet. And I cannot find out a perfect way to solve this issue. The simplest way out is do pip install bert-pytorch. or change the module name.

**Comment by ZhangZhuoSJTU** [comment]
Thanks for your reply!

I suppose the most convenient approach would be using the old code to load the model and dumping a new model via the up-to-date code.

**Comment by rellieberman** [comment]
Hi,
I'm also encountering 
`NameError: name 'bert_pytorch' is not defined`

when running train_palmtree.py
after manually importing bert-pytorch i get the following error:
`AttributeError: module 'bert_pytorch' has no attribute 'dataset'`

These both happen at this point in the code:
`test_dataset = bert_pytorch.dataset.BERTDataset(test_dataset, test_dataset, vocab, seq_len=20, on_memory=True) \
    if test_dataset is not None else None`

Should I be using an older version of bert_pytorch?

Thanks!

**Comment by yxy-whu** [comment]
> Thanks for your reply!
> 
> I additionally encounter a pickle unpacking error as follows
> 
> ```shell
> $ CUDA_VISIBLE_DEVICES="1" python how2use.py
> 
> Loading Vocab ./palmtree/vocab
> Traceback (most recent call last):
>   File "how2use.py", line 11, in <module>
>     palmtree = utils.UsableTransformer(model_path="./palmtree/transformer.ep19", vocab_path="./palmtree/vocab")
>   File "/PalmTree/PalmTree/eval_utils.py", line 59, in __init__
>     self.vocab = vocab.WordVocab.load_vocab(vocab_path)
>   File "/PalmTree/PalmTree/vocab.py", line 167, in load_vocab
>     return pickle.load(f)
> ModuleNotFoundError: No module named 'bert_pytorch'
> ```
> 
> I am using the pretrained model there. I search the codebase and cannot find the declaration of `bert_pytorch`. Would you mind helping me check what happened? Thanks for your time in advance.
> 
> https://github.com/palmtreemodel/PalmTree/blob/895828099a502195255e71a91f753f8cefe58349/src/train_palmtree.py#L40
> 
> https://github.com/palmtreemodel/PalmTree/blob/895828099a502195255e71a91f753f8cefe58349/src/train_palmtree.py#L52

First, thanks for the ingenious model.  I have this problem also when i change this model for myself dataset.  However, i have an solution that  I think will work. 

`ModuleNotFoundError: No module named 'bert_pytorch'` 
it is due to sys.path list lack of class modules of bert_pythorch when reading class instances stored in files.
So i add 
`import sys`
`sys.path.append('your/palmtree/root/path')`
when pickle module is loaded.
