### ISSUE TITLE
Unresolved reference 'registers' 

### ISSUE THREAD

**Issue by tyj1998** [palmtreemodel/PalmTree#6]
Unresolved reference 'registers' 
Hello, I am trying to reproduce your work with Pycharm in the windows10 environment, but #registers# and #memory_profiler# show Unresolved reference in dataflow_gen.py, I found #memory_profiler# in python but I am curious how I can find# registers# and how to import it.
THANKS!!

**Comment by iamawhalez** [comment]
i have the same problem, will you show me how to fix it? THANKS!!

**Comment by SidekickLx** [comment]
I forget one python file.
added
