### ISSUE TITLE
TypeError: parse_instruction() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by tyj1998** [palmtreemodel/PalmTree#7]
While generating the dataset I noticed that the function **def parse_instruction(ins, symbol_map, string_map)** in dataflow_gen.py, when called by the random_walk function **“s.append(parse_instruction(g.node[n]['text'], symbol_map , string_map, str_list))”**. There are four parameters and an error is reported. Is this parameter redundant, or is there an error in my calling method?

**Comment by SidekickLx** [comment]
It's my fault. That parameter is useless in this function and you can delete it. It should be a historical issue. Sorry about that.
