### ISSUE TITLE
About test dateset

### ISSUE THREAD

**Issue by tyj1998** [palmtreemodel/PalmTree#8]
Hello, when I have prepared the dataset to reproduce the training work, I find that I need a Test Dataset. 

'if test_dataset is not None else None' dose it mean it's necessary when training the model for the first time?

How to generate it if needed, or simply put the cfg and dfg data into one txt file? Thanks for your attention.

**Comment by SidekickLx** [comment]
test_dataset is just for training time validation and shows some statistics, so it is not necessary.
We have a data-flow and control-flow generator in the data_generator folder. You can use them to generate training and testing dataset.

**Comment by tyj1998** [comment]
Thanks for your reply, it helped me a lot
![014A2EDB](https://user-images.githubusercontent.com/51277261/171044588-3d79385f-2783-4c90-91e0-16ed6896464a.png)
